// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctopathII_Items.Data;

#nullable disable

namespace OctopathII_Items.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212021118_UpdatedMigrations")]
    partial class UpdatedMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OctopathII_Items.Models.Equipment", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Buy_Price")
                        .HasColumnType("int");

                    b.Property<int>("Critical")
                        .HasColumnType("int");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Elemental_Atk")
                        .HasColumnType("int");

                    b.Property<int>("Elemental_Def")
                        .HasColumnType("int");

                    b.Property<string>("Equipment_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Max_Hp")
                        .HasColumnType("int");

                    b.Property<int>("Max_SP")
                        .HasColumnType("int");

                    b.Property<int>("Physical_Atk")
                        .HasColumnType("int");

                    b.Property<int>("Physical_Def")
                        .HasColumnType("int");

                    b.Property<int>("Sell_Price")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("Elemental_Atk");

                    b.HasIndex("Equipment_Type");

                    b.HasIndex("Physical_Atk");

                    b.HasIndex("Sell_Price");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("OctopathII_Items.Models.Item", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Buy_Price")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Item_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sell_Price")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("Item_Type");

                    b.HasIndex("Sell_Price");

                    b.ToTable("Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
